#!/bin/sh
# ==============================================================================
# Telemt Entrypoint
#
# If config.toml is already mounted (volume mount), use it as-is.
# Otherwise, generate config.toml from environment variables.
# Then exec the telemt binary.
# ==============================================================================

set -e

CONFIG="/run/telemt/config.toml"

# --- If config.toml is already mounted, skip generation ---
if [ -f "$CONFIG" ]; then
    echo "[entrypoint] Found mounted config.toml — using it as-is"
    exec /app/telemt config.toml
fi

# --- Validate required environment variables ---
MISSING=0

if [ -z "$TELEMT_SECRET" ]; then
    echo "[entrypoint] ERROR: TELEMT_SECRET is required (32-hex, e.g. openssl rand -hex 16)"
    MISSING=1
fi

if [ -z "$TELEMT_SERVER_IP" ]; then
    echo "[entrypoint] ERROR: TELEMT_SERVER_IP is required (your server's public IP)"
    MISSING=1
fi

if [ -z "$TELEMT_PUBLIC_HOST" ]; then
    echo "[entrypoint] ERROR: TELEMT_PUBLIC_HOST is required (domain or IP for tg:// links)"
    MISSING=1
fi

if [ "$MISSING" -eq 1 ]; then
    echo "[entrypoint] See .env.example for documentation"
    exit 1
fi

# Validate secret format: exactly 32 hex characters
if ! echo "$TELEMT_SECRET" | grep -qE '^[0-9a-fA-F]{32}$'; then
    echo "[entrypoint] ERROR: TELEMT_SECRET must be exactly 32 hex characters"
    echo "[entrypoint] Got: '$TELEMT_SECRET' ($(echo -n "$TELEMT_SECRET" | wc -c) chars)"
    echo "[entrypoint] Generate with: openssl rand -hex 16"
    exit 1
fi

# --- Apply defaults for optional variables ---
TELEMT_TLS_DOMAIN="${TELEMT_TLS_DOMAIN:-www.google.com}"
TELEMT_USER_NAME="${TELEMT_USER_NAME:-main}"
TELEMT_PORT="${TELEMT_PORT:-443}"
TELEMT_PUBLIC_PORT="${TELEMT_PUBLIC_PORT:-$TELEMT_PORT}"
TELEMT_LOG_LEVEL="${TELEMT_LOG_LEVEL:-normal}"

# --- Generate config.toml ---
echo "[entrypoint] Generating config.toml from environment variables"

cat > "$CONFIG" << ENDOFCONFIG
# Auto-generated by entrypoint.sh from environment variables.
# To use a static config instead, mount config.toml as a volume.

[general]
use_middle_proxy = false
fast_mode = true
fast_mode_min_tls_record = 1400
log_level = "${TELEMT_LOG_LEVEL}"
desync_all_full = true
beobachten = true
beobachten_minutes = 30
beobachten_flush_secs = 15
beobachten_file = "cache/beobachten.txt"
ntp_check = true
ntp_servers = ["pool.ntp.org"]

[general.modes]
classic = false
secure = false
tls = true

[general.links]
show = "*"
public_host = "${TELEMT_PUBLIC_HOST}"
public_port = ${TELEMT_PUBLIC_PORT}

[server]
port = ${TELEMT_PORT}

[[server.listeners]]
ip = "0.0.0.0"
announce = "${TELEMT_SERVER_IP}"

[timeouts]
client_handshake = 15
tg_connect = 10
client_keepalive = 60
client_ack = 300

[censorship]
tls_domain = "${TELEMT_TLS_DOMAIN}"
mask = true
mask_port = 443
tls_emulation = true
tls_front_dir = "tlsfront"
fake_cert_len = 2048
server_hello_delay_min_ms = 50
server_hello_delay_max_ms = 150
tls_new_session_tickets = 2
tls_full_cert_ttl_secs = 0
alpn_enforce = true

[access]
replay_check_len = 65536
replay_window_secs = 1800
ignore_time_skew = false

[access.users]
${TELEMT_USER_NAME} = "${TELEMT_SECRET}"
ENDOFCONFIG

echo "[entrypoint] Config generated:"
echo "  secret:      ${TELEMT_USER_NAME} = ${TELEMT_SECRET:0:8}..."
echo "  server_ip:   ${TELEMT_SERVER_IP}"
echo "  public_host: ${TELEMT_PUBLIC_HOST}:${TELEMT_PUBLIC_PORT}"
echo "  tls_domain:  ${TELEMT_TLS_DOMAIN}"
echo "  log_level:   ${TELEMT_LOG_LEVEL}"
echo "[entrypoint] Starting telemt..."

exec /app/telemt config.toml
